yarnPath: .yarn/releases/yarn-4.3.1.cjs
# # nodeLinker: pnp

# packageExtensions:
#     '@prisma/client@*':
#         dependencies:
#             '.prisma': '*'
#     '@prisma/engines@*':
#         dependencies:
#             '.prisma': '*'
